/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "SimpleStorage"): TruffleContracts.SimpleStorageContract;
      require(
        name: "UpgradableStorage"
      ): TruffleContracts.UpgradableStorageContract;
    }
  }
}
